import { APP_NAME, APP_DOMAIN, APP_HOSTNAMES } from "./global/site";
import { LIST_ITEM_VARIANTS, CHILD_VARIANTS, FADE_IN_VARIANTS, MODAL_VARIANTS } from "./global/animation";

export {
  APP_NAME,
  APP_DOMAIN,
  APP_HOSTNAMES,
  LIST_ITEM_VARIANTS,
  CHILD_VARIANTS,
  FADE_IN_VARIANTS,
  MODAL_VARIANTS,
};
